### ISSUE TITLE
[Bug]调料合成后，产物出现异常动量

### ISSUE THREAD

**Issue by PigeonNian** [moelobster/AnvilCraft-Fooding#1]
OS Version - 操作系统
Windows

Minecraft Version Details - Minecraft 版本信息
1.20.1

Mod Loader - 模组加载器
Fabric

Existing behavior - 现有行为
无法正确产出，产物会直接飞起来！

Expected behavior - 预期行为
你自己写的自己知道

**Comment by moelobster** [comment]
已解决
